#!/usr/bin/env bash

set -euo pipefail

: "${CHECKSUMS_FILE:?CHECKSUMS_FILE is required}"
: "${NIGHTLY_TAG:?NIGHTLY_TAG is required}"
: "${NIGHTLY_VERSION:?NIGHTLY_VERSION is required}"
: "${OUTPUT_FILE:?OUTPUT_FILE is required}"

archive_sha() {
  local archive="$1"
  local sha

  sha="$(awk -v target="$archive" '$2 == target { print $1 }' "$CHECKSUMS_FILE")"

  if [[ -z "$sha" ]]; then
    printf 'missing checksum for %s in %s\n' "$archive" "$CHECKSUMS_FILE" >&2
    exit 1
  fi

  printf '%s\n' "$sha"
}

macos_amd64_archive="vigilante_${NIGHTLY_VERSION}_macOS_amd64.tar.gz"
macos_arm64_archive="vigilante_${NIGHTLY_VERSION}_macOS_arm64.tar.gz"
linux_amd64_archive="vigilante_${NIGHTLY_VERSION}_Linux_amd64.tar.gz"

macos_amd64_sha="$(archive_sha "$macos_amd64_archive")"
macos_arm64_sha="$(archive_sha "$macos_arm64_archive")"
linux_amd64_sha="$(archive_sha "$linux_amd64_archive")"

cat >"$OUTPUT_FILE" <<EOF
# This file was generated by the Vigilante nightly workflow. DO NOT EDIT.
cask "vigilante-nightly" do
  name "vigilante nightly"
  desc "Autonomous GitHub issue runner for headless coding agents"
  homepage "https://github.com/aliengiraffe/vigilante"
  version "${NIGHTLY_VERSION}"

  livecheck do
    skip "Rolling prerelease updated from main."
  end

  binary "vigilante"

  on_macos do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/${NIGHTLY_TAG}/${macos_amd64_archive}"
      sha256 "${macos_amd64_sha}"
    end
    on_arm do
      url "https://github.com/aliengiraffe/vigilante/releases/download/${NIGHTLY_TAG}/${macos_arm64_archive}"
      sha256 "${macos_arm64_sha}"
    end

    postflight do
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.provenance", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/codesign",
                     args:         ["--force", "--sign", "-", "#{staged_path}/vigilante"],
                     must_succeed: false
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/${NIGHTLY_TAG}/${linux_amd64_archive}"
      sha256 "${linux_amd64_sha}"
    end
  end

  # No zap stanza required
end
EOF
